### ISSUE TITLE
Only release from specific version of node

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/condition-circle#1]
specify in config, for example, release from Node 4

**Comment by tleunen** [comment]
Not especially required for circleci.

If you move your "semantic-release" in the deployment section instead of a `post-test`, it will be run when ALL tests will be successful, so if you run your tests against node 0.12, 4, 5, and 6 for example, you're sure the tests pass on all environments before deploying a new version

**Comment by bahmutov** [comment]
nice, thanks for pointing this @tleunen - this simplifies logic
